export const UPDATE_WEB3_DETAILS = 'UPDATE_WEB3_DETAILS';

// transfers
export const CREATE_TRANSFER = 'CREATE_TRANSFER';
export const CREATE_LINK_TRANSFER = 'CREATE_LINK_TRANSFER';
export const UPDATE_TRANSFER = 'UPDATE_TRANSFER';
export const UPDATE_BALANCE = 'UPDATE_BALANCE';
